name: Synchronizacja GQL.g4

on:
  workflow_dispatch: # Umożliwia ręczne uruchomienie workflow
  repository_dispatch:
    from: opengql/grammar # Uruchamia się, gdy opengql/grammar wyśle zdarzenie

jobs:
  sync-gql:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie pliku GQL.g4
        uses: actions/checkout@v3
        with:
          repository: opengql/grammar
          ref: master # gałąź z której pobieramy plik
          token: ${{ secrets.ACCESS_TOKEN }}
          path: opengql_grammar

      - name: Przeniesienie pliku GQL.g4
        run: |
          mv ./opengql_grammar/GQL.g4 ./

      - name: Commit i push zmian
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Zaktualizowano plik GQL.g4"
          branch: master
