name: Update GQL.g4

on:
  push:
    paths:
      - 'GQL.g4'

jobs:
  update-gql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if GQL.g4 exists
        run: |
          if [ ! -f "GQL.g4" ]; then
            wget -O GQL.g4 https://raw.githubusercontent.com/opengql/grammar/main/GQL.g4
          fi

      - name: Commit and push updated GQL.g4
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add GQL.g4
          git commit -m "Update GQL.g4 from opengql/grammar"
          git push

